###### Object detection config ######
--obstacle_detection
--nosimulator_obstacle_detection
--obstacle_detection_gpu_memory_fraction=0.2
--obstacle_detection_min_score_threshold=0.3
###### Traffic light detector config ######
--traffic_light_detection
--nosimulator_traffic_light_detection
--traffic_light_det_gpu_memory_fraction=0.2
--traffic_light_det_min_score_threshold=0.3
###### Lane detection config ######
--lane_detection
###### Depth #####
--perfect_depth_estimation
###### Segmentation config ######
--perfect_segmentation
###### Tracking config ######
# Tracking disabled - causes CUDA OOM with other operators
--perfect_obstacle_tracking
###### Prediction config ######
--prediction
--prediction_type=linear
--prediction_num_past_steps=10
--prediction_num_future_steps=10
###### Planning config #####
--planning_type=waypoint
###### Control config #####
--control=pid
###### Carla config ######
--simulator_num_people=30
--simulator_num_vehicles=30
--traffic_manager_port=8001
--camera_image_width=1280
--camera_image_height=720
######### Logging config #########
--log_file_name=pylot_timing_analysis.log
--csv_log_file_name=pylot_timing_analysis.csv
--profile_file_name=pylot_timing_analysis_profile.json
--v=1
######### Deadline config (visibility only, no enforcement) #########
--deadline_enforcement=none
######### Other config #########
#--visualize_detected_obstacles
#--visualize_detected_traffic_lights
