--obstacle_detection
--nosimulator_obstacle_detection
--obstacle_detection_model_paths=ws_maskformer
--obstacle_detection_model_names=ws_maskformer
--ws_maskformer_config_path=../wsobjdet/sem_ade_output_2/config.yaml
--ws_maskformer_weights_path=../wsobjdet/sem_ade_output_2/model_final.pth
--ws_maskformer_repo_root=../wsobjdet
--ws_maskformer_subnet=max
--obstacle_detection_min_score_threshold=0.3
--obstacle_detection_gpu_memory_fraction=0.9
###### Control config #####
--control=simulator_auto_pilot
######### Carla config #########
--simulator_num_people=250
--simulator_num_vehicles=20
######### Logging config #########
--log_file_name=pylot_wsdet.log
--csv_log_file_name=pylot_wsdet.csv
--v=1
######### Other config #########
#--visualize_rgb_camera
#--visualize_detected_obstacles
